
FROM ghost:5-alpine


WORKDIR /var/lib/ghost

# Optionnel :copier un thème personnalisé ici
# COPY ./mon-theme-custom ./content/themes/mon-theme-custom

# On expose le port par défaut
EXPOSE 2368

# Commande de lancement par défaut de l'image parente
CMD ["node", "current/index.js"]