---
ghost_app_dir: /opt/ghostblog
ghost_app_db_host: ""
ghost_app_db_port: 3306
ghost_app_db_name: ghost_db
ghost_app_db_user: ""
ghost_app_db_password: ""
ghost_app_url: "http://localhost:8090"
ghost_app_image_tag: latest
ghost_app_registry_url: ""
ghost_app_registry_user: ""
ghost_app_registry_password: ""
